apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-container
        image: fastapi-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        readinessProbe:                   # ✅ added readiness probe
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: ClusterIP    # change to NodePort if you want to expose it outside the cluster
  selector:
    app: fastapi-app
  ports:
  - port: 80
    targetPort: 80
