# ---------------------------------------
# ConfigMap
# ---------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  APP_ENV: "development"
  APP_DEBUG: "true"
  WELCOME_MESSAGE: "Hello from ConfigMap 👋"
  # Could put entire config files here as well
  CONFIG_YAML: |
    server:
      host: 0.0.0.0
      port: 80

---
# ---------------------------------------
# Secret used for sensitive data, 
# use stringData for easier input, KUBECTL will encode it to base64
# ---------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
type: Opaque
stringData:
  USERNAME: admin
  PASSWORD: s3cr3tP@ss

---
# ---------------------------------------
# Deployment: test ConfigMap & Secret usage by busybox
# ---------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-container
        image: busybox
        command: ["/bin/sh", "-c", "sleep 3600"]   # Keep the container running for demo
        envFrom:
          - configMapRef:
              name: demo-config
          - secretRef:
              name: demo-secret
        volumeMounts:
          - name: config-volume
            mountPath: /etc/demo-config
          - name: secret-volume
            mountPath: /etc/demo-secret
            readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: demo-config
        - name: secret-volume
          secret:
            secretName: demo-secret

---
# ---------------------------------------
# Service ：demo cluster-internal access
# ---------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP
