apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapi-chart.fullname" . }}-secret
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: "{{ $value }}"
{{- end }}
